name: Compile 

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 3
      matrix:
        gcc-version: [arm-eabi-4.8, arm-linux-androideabi-4.9, arm-linux-gnueabihf]

    steps:
    - uses: actions/checkout@v2
      
    - run: sudo mkdir /gcc && cd /gcc # GCC folder
      
    - if: matrix.gcc-version == 'arm-eabi-4.8'
      name: Download arm-eabi-4.8 cross compiler
      run: git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-eabi-4.8/
    
    - if: matrix.gcc-version == 'arm-linux-androideabi-4.9'
      name: Download arm-linux-androideabi-4.9 cross compiler
      run: git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9
    
    - if: matrix.gcc-version == 'arm-linux-gnueabihf'
      name: Download arm-linux-gnueabihf (gcc-linaro-7.5.0) cross compiler
      run: |
          wget https://releases.linaro.org/components/toolchain/binaries/latest-7/arm-linux-gnueabihf/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf.tar.xz
          tar -xvf gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf.tar.xz
          cd gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf
          ls
    
    #- run: 
      
      
    #- name: make
      #run: make
    #- name: make check
      #run: make check
    #- name: make distcheck
      #run: make distcheck
